---
- name: Gather current containers
  uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/storage_containers"
    method: GET
    validate_certs: "{{ role_nutanix_pe_container_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 200
    return_content: true
  register: role_nutanix_pe_container_current_list
  ignore_errors: false

- name: Debug get_containers.yml variables
  debug:
    var: role_nutanix_pe_container_current_list.json
  when:
    - role_nutanix_pe_container_debug

- name: Gather default container uuid
  ansible.builtin.set_fact:
    role_nutanix_pe_container_default_uuid: "{{ item }}"
  with_items: "{{ role_nutanix_pe_container_current_list.json | to_json | from_json | json_query(query) }}"
  vars:
    query: "entities[?contains(name, 'default-container-')].storage_container_uuid"
  when: role_nutanix_pe_container_current_list.json.metadata.total_entities > 0

- name: Delete default container
  ansible.builtin.uri:
    url: "https://{{ role_nutanix_prism_api_url_base }}/PrismGateway/services/rest/v2.0/storage_containers/{{ role_nutanix_pe_container_default_uuid }}"
    method: DELETE
    validate_certs: "{{ role_nutanix_pe_container_host_validate_certs }}"
    body_format: json
    headers:
      Authorization: "{{ role_nutanix_prism_api_auth_string_b64 }}"
    status_code: 204
    return_content: true
  register: role_nutanix_pe_container_default_delete_task
  ignore_errors: false
  when: role_nutanix_pe_container_default_uuid is defined

- name: Debug remove_default_container.yml variables
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - role_nutanix_pe_container_default_uuid
    - role_nutanix_pe_container_default_delete_task.json
  when:
    - role_nutanix_pe_container_debug
